version: '3'
services:
  web:
    build: .
    volumes:
    - ./sets:/app/sets
    environment: 
    - RAILS_ENV=production
    - DATABASE_URL=mysql2://arena:arena@mysql:3306/arena?encoding=utf8&collation=utf8_general_ci
    - SECRET_KEY_BASE=cc8aa5eba1ab517a3b6d08eb72652cf8cbe7ba2e6da67090932fb66daf4b45e413c9c5994dea2f566d3f705341e32637bffd69824277ab189c83988826ec06a8
    - SECRET_TOKEN=5b7fb3a584b436a54ae5cec3b5ccfa393575900ffcc869cc37da4632f4023f80
    - REDIS_PROVIDER=redis://redis:6379
    - MEMCACHE_URL=memcached:11211
    - SIDEKIQ_USERNAME=arena
    - SIDEKIQ_PASSWORD=arena
    links:
    - redis
    - mysql
    - memcached
    ports: 
    - 8080:8080
    tmpfs:
    - /app/tmp
  sidekiq:
    build: .
    command: "sidekiq --P /app/tmp/sidekiq.pid"
    environment:
    - RAILS_ENV=production
    - DATABASE_URL=mysql2://arena:arena@mysql:3306/arena?encoding=utf8&collation=utf8_general_ci
    - REDIS_PROVIDER=redis://redis:6379
    tmpfs:
    - /app/tmp
  redis:
    image: redis:alpine
  memcached:
    image: memcached:alpine
  mysql:
    image: mariadb
    volumes:
    - ./data/db:/var/lib/mysql
    environment: 
    - MYSQL_DATABASE=arena
    - MYSQL_USER=arena
    - MYSQL_PASSWORD=arena
    - MYSQL_ROOT_PASSWORD=arena
    command: "--collation-server=utf8_general_ci --character-set-server=utf8"